# Generated by Django 2.2.7 on 2020-09-16 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FoodName', models.CharField(max_length=200)),
                ('FoodPrice', models.IntegerField(default=0)),
                ('FoodCalories', models.IntegerField(default=0)),
                ('FoodType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.FoodType')),
            ],
        ),
    ]
