# Generated by Django 2.2.7 on 2020-10-16 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calorie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Calorie', models.IntegerField(default='แคลลอรี่')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Food_Name', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('Calorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.Calorie')),
            ],
        ),
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Food_Type', models.CharField(default='ประเภทอาหาร', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='food',
            name='FoodType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myweb.FoodType'),
        ),
    ]
